# Generated by Django 5.1 on 2024-12-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_chat_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="role",
            field=models.CharField(default="user", max_length=11),
        ),
    ]
