# Generated by Django 5.1 on 2024-12-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_participant_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customauthtoken",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
