# Generated by Django 5.1 on 2024-12-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customauthtoken_google_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customauthtoken",
            name="google_id",
        ),
        migrations.AddField(
            model_name="customuser",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
