# Generated by Django 5.1 on 2024-12-05 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_tasks_order_tasks"),
        ("tasks", "0002_initial"),
        ("users", "0002_remove_team_members_teammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_order",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_team",
                to="users.team",
            ),
        ),
    ]
