# Generated by Django 5.1 on 2024-12-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="tasks",
        ),
        migrations.AddField(
            model_name="order",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="orders", to="tasks.task"
            ),
        ),
    ]
