# Generated by Django 5.1 on 2024-12-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_tasks_order_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
    ]
