# Generated by Django 5.1 on 2024-12-13 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_status"),
        ("tasks", "0003_task_order_alter_task_team"),
        ("users", "0003_team_list_of_members_delete_teammember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="orders", to="tasks.task"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="team",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_orders",
                to="users.team",
            ),
        ),
    ]
