# Generated by Django 5.1 on 2024-12-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="on_delete_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
